#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
    path: /logout
    methods: GET

login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST